modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"
[[mods]]

modId = "limitedspawners"
version = "${file.jarVersion}"
displayName = "Limited Spawners"
description = '''
This mods limits the no of mobs a mob spawner can spawn
'''
[[dependencies.limitedspawners]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.limitedspawners]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,]"
ordering = "NONE"
side = "BOTH"
