name: "Build Release"
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
jobs:
  build-release:
    uses: StrikerRockers-Mods/.github/.github/workflows/builld-release-forge.yml@main
    secrets: inherit
    with:
      forge-cf-id: 410922
      modrinth-id: NeO7lLvU
