name: "Build Release"
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
jobs:
  build-release:
    uses: StrikerRockers-Mods/.github/.github/workflows/build-release-v2.yml@main
    secrets: inherit
    with:
      forge-cf-id: 410922
      fabric-cf-id: 429084
      modrinth-id: NeO7lLvU
      fabric-dependencies: |
        cloth-config | depends | *
        modmenu | recommends | *